// Request: Get temperature by zipcode
// Method: GET
// URL: http://localhost:8080/temperature/{zipcode}
GET http://localhost:8080/temperature/59010020 HTTP/1.1
Host: localhost:8080
Content-Type: application/json