// Request: POST temperature by zipcode
// Method: POST
// URL: http://localhost:8080/temperature
POST http://localhost:8080/temperature HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "cep": "59010020"
}

//curl -X POST http://localhost:8080/temperature -H "Content-Type: application/json" -d '{"cep": "59010020"}'